//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TideScraper.Services.PredictionsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl", ConfigurationName="PredictionsService.PredictionsPortType")]
    public interface PredictionsPortType {
        
        // CODEGEN: Generating message contract since the operation getPredictions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TideScraper.Services.PredictionsService.getPredictionsResponse getPredictions(TideScraper.Services.PredictionsService.getPredictionsRequest request);
        
        // CODEGEN: Generating message contract since the operation getPredictionsAndMetadata is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TideScraper.Services.PredictionsService.getPredictionsAndMetadataResponse getPredictionsAndMetadata(TideScraper.Services.PredictionsService.getPredictionsAndMetadataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl")]
    public partial class Parameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stationIdField;
        
        private string beginDateField;
        
        private string endDateField;
        
        private int datumField;
        
        private int unitField;
        
        private int timeZoneField;
        
        private int dataIntervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
                this.RaisePropertyChanged("stationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
                this.RaisePropertyChanged("beginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("timeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int dataInterval {
            get {
                return this.dataIntervalField;
            }
            set {
                this.dataIntervalField = value;
                this.RaisePropertyChanged("dataInterval");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl")]
    public partial class Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string timeStampField;
        
        private double predField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double pred {
            get {
                return this.predField;
            }
            set {
                this.predField = value;
                this.RaisePropertyChanged("pred");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl")]
    public partial class PredictionsValues : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Data[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Data[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPredictionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl", Order=0)]
        public TideScraper.Services.PredictionsService.Parameters Parameters;
        
        public getPredictionsRequest() {
        }
        
        public getPredictionsRequest(TideScraper.Services.PredictionsService.Parameters Parameters) {
            this.Parameters = Parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPredictionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl", Order=0)]
        public TideScraper.Services.PredictionsService.PredictionsValues PredictionsValues;
        
        public getPredictionsResponse() {
        }
        
        public getPredictionsResponse(TideScraper.Services.PredictionsService.PredictionsValues PredictionsValues) {
            this.PredictionsValues = PredictionsValues;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl")]
    public partial class PredictionsAndMetadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stationIdField;
        
        private string stationNameField;
        
        private float latitudeField;
        
        private float longitudeField;
        
        private string stateField;
        
        private string dataSourceField;
        
        private string cOOPSDisclaimerField;
        
        private string beginDateField;
        
        private string endDateField;
        
        private string datumField;
        
        private string unitField;
        
        private string timeZoneField;
        
        private string dataIntervalField;
        
        private Data[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
                this.RaisePropertyChanged("stationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string stationName {
            get {
                return this.stationNameField;
            }
            set {
                this.stationNameField = value;
                this.RaisePropertyChanged("stationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
                this.RaisePropertyChanged("dataSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string COOPSDisclaimer {
            get {
                return this.cOOPSDisclaimerField;
            }
            set {
                this.cOOPSDisclaimerField = value;
                this.RaisePropertyChanged("COOPSDisclaimer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
                this.RaisePropertyChanged("beginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("timeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dataInterval {
            get {
                return this.dataIntervalField;
            }
            set {
                this.dataIntervalField = value;
                this.RaisePropertyChanged("dataInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Data[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPredictionsAndMetadataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl", Order=0)]
        public TideScraper.Services.PredictionsService.Parameters Parameters;
        
        public getPredictionsAndMetadataRequest() {
        }
        
        public getPredictionsAndMetadataRequest(TideScraper.Services.PredictionsService.Parameters Parameters) {
            this.Parameters = Parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPredictionsAndMetadataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opendap.co-ops.nos.noaa.gov/axis/webservices/predictions/wsdl", Order=0)]
        public TideScraper.Services.PredictionsService.PredictionsAndMetadata PredictionsAndMetadata;
        
        public getPredictionsAndMetadataResponse() {
        }
        
        public getPredictionsAndMetadataResponse(TideScraper.Services.PredictionsService.PredictionsAndMetadata PredictionsAndMetadata) {
            this.PredictionsAndMetadata = PredictionsAndMetadata;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PredictionsPortTypeChannel : TideScraper.Services.PredictionsService.PredictionsPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PredictionsPortTypeClient : System.ServiceModel.ClientBase<TideScraper.Services.PredictionsService.PredictionsPortType>, TideScraper.Services.PredictionsService.PredictionsPortType {
        
        public PredictionsPortTypeClient() {
        }
        
        public PredictionsPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PredictionsPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PredictionsPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PredictionsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TideScraper.Services.PredictionsService.getPredictionsResponse TideScraper.Services.PredictionsService.PredictionsPortType.getPredictions(TideScraper.Services.PredictionsService.getPredictionsRequest request) {
            return base.Channel.getPredictions(request);
        }
        
        public TideScraper.Services.PredictionsService.PredictionsValues getPredictions(TideScraper.Services.PredictionsService.Parameters Parameters) {
            TideScraper.Services.PredictionsService.getPredictionsRequest inValue = new TideScraper.Services.PredictionsService.getPredictionsRequest();
            inValue.Parameters = Parameters;
            TideScraper.Services.PredictionsService.getPredictionsResponse retVal = ((TideScraper.Services.PredictionsService.PredictionsPortType)(this)).getPredictions(inValue);
            return retVal.PredictionsValues;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TideScraper.Services.PredictionsService.getPredictionsAndMetadataResponse TideScraper.Services.PredictionsService.PredictionsPortType.getPredictionsAndMetadata(TideScraper.Services.PredictionsService.getPredictionsAndMetadataRequest request) {
            return base.Channel.getPredictionsAndMetadata(request);
        }
        
        public TideScraper.Services.PredictionsService.PredictionsAndMetadata getPredictionsAndMetadata(TideScraper.Services.PredictionsService.Parameters Parameters) {
            TideScraper.Services.PredictionsService.getPredictionsAndMetadataRequest inValue = new TideScraper.Services.PredictionsService.getPredictionsAndMetadataRequest();
            inValue.Parameters = Parameters;
            TideScraper.Services.PredictionsService.getPredictionsAndMetadataResponse retVal = ((TideScraper.Services.PredictionsService.PredictionsPortType)(this)).getPredictionsAndMetadata(inValue);
            return retVal.PredictionsAndMetadata;
        }
    }
}
